name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  # This triggers the action on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH agent and add the EC2 SSH key
    - name: Start SSH agent and add the EC2 key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

    # Step 3: SSH into the EC2 instance, pull the latest code, install dependencies, and restart the app
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Navigate to the application directory (if exists) or clone the repo
          if [ -d "/home/ubuntu/conqt" ]; then
            cd /home/ubuntu/conqt
            git pull origin main
          else
            git clone https://github.com/EshanDev-ConQT/node-js-AWS.git /home/ubuntu/conqt
            cd /home/ubuntu/conqt
          fi

          # Install Node.js dependencies
          # npm install

          # Restart the Node.js app using PM2
          # pm2 restart all || pm2 start hello.js --name "hello"
          node hello.js

        EOF